### ISSUE TITLE
Copying to container from Reader?

### ISSUE THREAD

**Issue by matthiasbeyer** [softprops/shiplift#236]
I'd like to have a function to copy file(s) to the container from a Reader, so I do not have to read the whole file into memory.

Right now, copying to the container is:

1. Read the whole file into memory
1. Copy it to the container

What I'd like:

1. Pass a `std::io::Read` to shiplift, maybe even an async version (`async_std::io::Read` or the tokio equiv.)

And let the runtime do the thing, no need to read the whole (possibly massive) file into memory.

---

Possibly some more rationale. I am currently doing some research for developing an application that would need to start N containers and copy several large files into the containers. Possibly multiple GB overall. That _could_ lead to a OOM situation, especially when doing everything asynchronously and having multiple copy-processes simultanously.
Having such a feature could help with this.

**Comment by elihunter173** [comment]
We could implement this, but sadly it would still have to read the entire file into memory. This is because `Container::copy_file_into` is essentially just a wrapper around `PUT /containers/{id}/archive` from the [Docker API](https://docs.docker.com/engine/api/v1.40/#operation/PutContainerArchive). As far as I can tell, there is no other API endpoint that allows you to upload files to the container's filesystem.

So the function would really just hide reading the file into memory, which I think would make the edge case you mentioned of running out of memory even harder to debug. It could still be implemented as a minor ergonomics boost, but I think that [`std::fs::read`](https://doc.rust-lang.org/std/fs/fn.read.html) already serves this purpose well.

**Comment by matthiasbeyer** [comment]
Agreed. Sad that there is no streaming interface for uploading a file. I would not implement such an interface in shiplift because, as you said, that might make debugging a lot harder.

I guess we can close this issue now?

**Comment by elihunter173** [comment]
I think so
