### ISSUE TITLE
Bad documentation link in REDME.md !

### ISSUE THREAD

**Issue by lowlevl** [softprops/shiplift#90]
It links to the old doc repository, the docs.rs one is more up to date !

**Comment by softprops** [comment]
Both are valid. I publish docs docs by default on pushes to master to gh pages. Docs.rs on builds docs for published releases. I'll add a link to doc.rs for clarity

**Comment by Nurrl** [comment]
Actually, the gh-page is outdated for now ^^

Le 24 août 2018 14:55, "doug tangren" <notifications@github.com> a écrit :

Both are valid. I publish docs docs by default on pushes to master to gh
pages. Docs.rs on builds docs for published releases. I'll add a link to
doc.rs for clarity

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/softprops/shiplift/issues/90#issuecomment-415750406>,
or mute the thread
